### ISSUE TITLE
Deal with removal of smart_open.tests subpackage

### ISSUE THREAD

**Issue by mpenkov** [conda-forge/smart_open-feedstock#38]
Looks like the feedstock depends on this subpackage, but it's not there anymore.

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=297478&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d&l=731

**Comment by rwedge** [comment]
Currently the test section for this recipe is

```yaml
test:
  requires:
    - mock
    - responses
  imports:
    - smart_open
    - smart_open.tests
 ```

would it be sufficent to remove the `smart_open.tests` import?
